### ISSUE TITLE
Items should be loaded from chunk store

### ISSUE THREAD

**Issue by huin** [huin/chunkymonkey#56]

**Comment by huin** [comment]
Pointers on implementing this (also applicable to loading other things from chunk store):
- chunkymonkey/chunkstore.IChunkReader.GetRootTag
- The inspectlevel utility to look at what's in a chunk
- chunkymonkey/shardserver.newChunkFromReader

Feel free to ask questions on this, or unassign if not to your taste.

**Comment by jnwhiteh** [comment]
I've completed this change (for items only, without velocity data) and this can be viewed and tested in commit https://github.com/jnwhiteh/chunkymonkey/commit/bb282fae8b8b49689cd60839aca8bca25bd026d0 on my fork. I haven't pushed it here because it includes a terminology change that I'd like someone to look at before pushing it to the main repository.

The code works properly for the cases I have tested. I'd like to create some tests for this, but it's rather difficult given that it relies on chunk data and possibly the gameRules and an entity manager. I may work on some framework for that and put it in place once I've loaded the other types of entities.

Just ping me back with an approval and I'll push the code here as well.

Note to myself, the other entities are all either mobs or other objects that are not placed blocks (boat, minecart, thrown arrow, activated tnt, etc.)

**Comment by jnwhiteh** [comment]
I've just implemented support for all of the known ObjectTypeIds, so we have mobs, items, and objects (minecarts, boats, etc.) working properly. The physics of the objects are not implemented so they're a bit weird, but they load properly. It's on my fork, again.

**Comment by jnwhiteh** [comment]
Committed as 6a23429d465b294f7df6
