### ISSUE TITLE
Cannot intercept chunkymonkey

### ISSUE THREAD

**Issue by jnwhiteh** [huin/chunkymonkey#73]
If I run an intercept on a chunkymonkey (HEAD) server, I cannot properly login:

2011/07/11 17:55:45.981646 Listening on :25565
[1] 2011/07/11 17:55:50.052700 Client connected from 127.0.0.1:51723
[1] 2011/07/11 17:55:50.052778 Creating relay to server localhost:25566
[1] 2011/07/11 17:55:50.054442 Connected to server
[1](C->S) 2011/07/11 17:55:50.055424 ServerReadHandshake(username=jnwhiteh)

The client eventually disconnects with a client socket timeout. Can anyone else reproduce this issue, or do I have something borked in my world?

**Comment by huin** [comment]
I think I had a similar problem with some code I pushed to head on Sunday. I
thought I had pushed a fix for this. Is it still not working?

**Comment by jnwhiteh** [comment]
This is synched with your HEAD following a make clean/make.

**Comment by huin** [comment]
Okay, clearly I've broken something. Will look when I get home from work.

**Comment by huin** [comment]
Works okay for me. One thing I'm curious about is what parameters you used to start the server with. The intercept proxy looks like it's been run with localhost:25565 and localhost:25566 - which implies that the server should have specified: -addr :25566 and -http_addr :$ANYTHING_ELSE

The default port for the HTTP server is 25566, which the intercept might be connecting to instead of the game port.

**Comment by jnwhiteh** [comment]
ah, okay.. I'll take a look at that.

**Comment by jnwhiteh** [comment]
Yeah, I normally do it in the other direction, dont' know why I did it this way this time. Sorry about that!
